### ISSUE TITLE
[REQUEST] Incorporate Nextclade 

### ISSUE THREAD

**Issue by molly-hetheringtonrauth** [CDPHE-bioinformatics/CDPHE-RSV#1]
### Feature Request
We want to incorporate nextclade into the RSV workflow. 

### Solution
1) we need to update the nextclade json parser python script to inlcude RSV as an organism option. 
2) we need to incorporate nextclade into the assembly workflow because, we will need to know the type (A or B) in order to use the correct nextclade dataset. Then we can merge the results in the summary results workflow. 

### Upstream effects
none.

### Downstream effects
none.

**Comment by danpolanco** [comment]
We are changing directions and getting rid of `nextclade_json_parser.py`. So instead, we are going to put  clade, G_clade, total substitutions, etc in the `summary.py`.

**Comment by molly-hetheringtonrauth** [comment]
We will pull the clade, G clade, total substitutions from the nextclade.csv output. We will need to refactor the summary.py script.
